project:
  name: test
cluster:
  name: test1
  id: 2
  vip: 192.168.3.210

nginx:
  ip:
    public: 192.168.3.211
    private:
  domain:
    public: test.galuzin.dev
    private: test1.home

monitoring:
  alertmanager:
    slack_api_url: https://hooks.slack.com/services/
    slack_channel: monitoring
    slack_username: test-cluster
  grafana:
    adminPassword: q1w2e3r4
  prometheus:
    retention: 30d
    retentionSize: 9GB
    storage: 10G
    storageClassName: mayastor-3
  vm:
    retentionPeriod: 3
    storageClass: mayastor-3
    size: 16G


