{{- if .Values.storage.enable }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "teamcity-server.fullname" . }}-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.storageClass }}
{{- end }}