version: '3.7'
services:
  dns:
    restart: always
    image: quay.io/poseidon/dnsmasq
    network_mode: host
    cap_add:
      - NET_ADMIN
    command:
      - -d
      - --dhcp-range=192.168.3.101,192.168.3.150
      - --dhcp-option=1,255.255.255.0
      - --dhcp-option=3,192.168.3.1
      - --enable-tftp
      - --tftp-root=/var/lib/tftpboot
      - --dhcp-match=set:bios,option:client-arch,0
      - --dhcp-boot=tag:bios,undionly.kpxe
      - --dhcp-match=set:efi32,option:client-arch,6
      - --dhcp-boot=tag:efi32,ipxe.efi
      - --dhcp-match=set:efibc,option:client-arch,7
      - --dhcp-boot=tag:efibc,ipxe.efi
      - --dhcp-match=set:efi64,option:client-arch,9
      - --dhcp-boot=tag:efi64,ipxe.efi
      - --dhcp-userclass=set:ipxe,iPXE
      - --dhcp-boot=tag:ipxe,http://192.168.3.100:8080/boot.ipxe
      - --log-queries
      - --log-dhcp
      - --dhcp-host=12:8d:a7:33:cc:e4,192.168.3.101
      - --dhcp-host=12:93:4b:39:8b:e7,192.168.3.102
      - --dhcp-host=12:c2:e1:db:62:03,192.168.3.103
      - --dhcp-host=12:f4:89:89:0a:34,192.168.3.111
      - --dhcp-host=12:f3:66:30:06:3b,192.168.3.112
      - --dhcp-host=12:d5:67:aa:b9:5c,192.168.3.113
  matchbox:
    restart: always
    image: quay.io/poseidon/matchbox:v0.10.0
    network_mode: host
    command:
      - -address=0.0.0.0:8080
      - -rpc-address=0.0.0.0:8081
      - -log-level=debug
    volumes:
      - /data/volumes/matchbox/var/lib/matchbox:/var/lib/matchbox
      - /data/volumes/matchbox/etc/matchbox:/etc/matchbox
