kind: Pod
apiVersion: v1
metadata:
  name: fio
spec:
  # Run on a storage node so that the nexus is local to the app
  nodeSelector:
    openebs.io/engine: mayastor
  volumes:
    - name: ms-volume
      persistentVolumeClaim:
       claimName: ms-volume-claim
    - name: scratch-data
      emptyDir: {}
    - name: shm
      emptyDir:
        medium: Memory
  containers:
    - name: fio
      image: mayadata/fio
      args:
        - sleep
        - "1000000"
      volumeMounts:
        - mountPath: "/volume"
          name: ms-volume
        - name: scratch-data
          mountPath: /run
        - name: scratch-data
          mountPath: /controller
        - name: shm
          mountPath: /dev/shm
      #volumeDevices:
      #  - devicePath: /dev/xvda
      #    name: ms-volume
