---
bases:
  - envs/environments-full.yaml

---
releases:
  - name: kaui
    namespace: kafka
    chart: akhq/akhq
    version:
    values:
      - existingSecrets: ""
        secrets:
          akhq:
            connections:
              dev-clustert:
                properties:
                  bootstrap.servers: 10.5.80.93:9092
        ingress:
          enabled: true
          ingressClassName: "nginx"
          annotations: {}
          paths:
            - /
          hosts:
            - akhq.trn01-lc-stakelogic.com
