---
bases:
  - envs/environments.yaml

---
releases:
  - name: kaui
    namespace: kafka
    chart: akhq/akhq
    version:
    values:
      - existingSecrets: ""
        secrets:
          akhq:
            connections:
              test-clustert:
                properties:
                  bootstrap.servers: kafka1-kafka-bootstrap:9092
                schema-registry:
                  url: http://schema:8080
                  type: "confluent"
                connect:
                  - name: "dev-connect"
                    url: http://connect:8083
        ingress:
          enabled: true
          ingressClassName: "nginx"
          annotations: {}
          paths:
            - /
          hosts:
            - akhq.test.home
