bases:
  - envs/environments.yaml

---
releases:
  - name: bitbucket
    namespace: cicd
    chart: atlassian-data-center/bitbucket
    version: 
    values:
      - replicaCount: 1
        image:
          repository: atlassian/bitbucket-server
          tag: latest
        service:
          type: ClusterIP
          port: 80
        ingress:
          create: true
          host: bitbucket.test.home
