---
bases:
  - envs/environments.yaml

---
releases:
  - name: ha
    namespace: harbor
    chart: harbor/harbor
    version:
    values:
      - expose:
          type: ingress
          tls:
            enabled: true
            certSource: secret
            secret:
              secretName: "harbor.{{ .Values.nginx.domain.public }}-tls"
              notarySecretName: "notary.{{ .Values.nginx.domain.public }}-tls"
            auto:
              commonName: ""
          ingress:
            hosts:
              core: harbor.{{ .Values.nginx.domain.public }}
              notary: notary.{{ .Values.nginx.domain.public }}
            controller: default
            annotations:
              ingress.kubernetes.io/ssl-redirect: "true"
              ingress.kubernetes.io/proxy-body-size: "0"
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
              kubernetes.io/ingress.class: nginx
              kubernetes.io/tls-acme: "true"
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              cert-manager.io/cluster-issuer: letsencrypt-prod
        externalURL: https://harbor.{{ .Values.nginx.domain.public }}
        persistence:
          enabled: true
          imageChartStorage:
            disableredirect: false
            type: gcs
            gcs:
              bucket: shining-lamp-369509-dev-harbor-bucket
              encodedkey: |
                ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAic2hpbmluZy1s
                YW1wLTM2OTUwOSIsCiAgInByaXZhdGVfa2V5X2lkIjogIjY5OWMxMjVkYzMwYjQ2ZWRhZTNiYTk2
                MmNkYjcyYzM1MTBkYTMwZjMiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUg
                S0VZLS0tLS1cbk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9J
                QkFRQ2J4WDBLSzVNU2ZHK2RcbjE2SlQyemg1L0VEK1hKb1JjTDI1YkJjeHZYVUZLbmVyT3hLU3Bt
                UENuYjh4aS9RTml4TEVWWnJ1T1FlbEV3TnRcblRLeDVLZSthQ2pZOWcyK0tBU0JDZUNZTzVPdzhO
                SjhUT2pHdGxoTEc3R09qaXU1M2hVR05CbXhDOERvQ1pGa0xcbnU4SjY4d2hxSkwrU29BeVAxR1lv
                M05GT1YrUmRXVHc4THBKMTZSQktXQkNiSkNqT0F3WUpDNi9hUEliTUNVK2tcbk5Gbm1JWkJEN054
                WTF2blJqNHpNaDVRbDVqTzUzVndRMlA2Q1FYN3hPMG95dDZ3VWZON3BNVElBWjFLOXF4N29cbmJY
                Nk5ac09rcGRMUDM5eXRJRFhWaGpvREVIUVNlQTdxelQwVmZnNW9lNTRiSTc2KzdCQjdicFdyTDNv
                RkFXUTFcbnd3NTZxUnBkQWdNQkFBRUNnZ0VBQW9uelVmS2RpT0Z1cWtwdm5XRkhLRFIvS2dZcXNW
                cHBPbzFJb0NscWhRVXpcbnJSNmZNZ3BmT1l2N3AvR1VMcEpUNGMrcFlQVHlBSFB4REREWE8zbXBB
                T3JtQm11a0trSXBjSnZudHVURDlaay9cbjl5bHRmTnI0MUdBdTl1VkJUTUVSd3B3cnNJMmN6Rzda
                UlYwdjVzbHc4Tlh5S2hBaUZFZ055dUJmMHZYbUdzcXpcbjNha0JrYWx6ZmlJRFJTeUxZWHJrS2lu
                VDJvdkpla2piUTZhc1FocTZkb1BOYm93aGNvTXlWeXgwVSsxRkYzR0hcblJ4MlV3QmswYVBLNyti
                WFJRbVlUN2hWcll1Z3pFaEh5bURwWmo2bWlpMGFIekwwOHd2ZU1ST011VFpMZTdEYmJcbnBXWEhQ
                WjE4SE1yL01UQzZRcHRPQnVuN20rbE14RWJKbklYUUFOZmN1d0tCZ1FETmZ5aFpYd3BPR0Y2cVQ4
                cUpcbkNIZmRXYXVoMHRDcElUTVdzaFpPVTVPMEhqcmlJOGE2c1JQWWdHVWFxZVFWRDlvREdNNEVh
                YThuMzdHczE1Y09cbkd1QUxxU0lEd0FjQzJ0cERDYW1MNTZGWWxXTnlJR2pOTlJJSTJob0hBSWtR
                aTlYWjBoK1lEUi92d0ZPRGZiaE5cbmNIdTBNZ2VoZXEzZXVydURQL0JUMDJTVEV3S0JnUURDRGR5
                QnRQYUhMWlErdnNDV0R6YjJiREVKYlFFMXptTDVcbkNLa212Mm9OMitVeXVVMXhHaTF6R2FlbG5H
                RWFEek8wMkZ4K2xpcHh0dDdWU21hUTVzeFJ5eVBNZ3JQTXpqMkxcbjVvY2Z2YnI3dDdsNDNkNzBR
                aGpTOXRkU3FnMHprcXRaR3J2S3BUYUZVMmpiUWxPNlV0RXhOdnhXbUxPZEViMU1cbk53ZWJ4NGph
                endLQmdCcWhhT3cwQ2RUWENhV09rNU93bWtBQU4rTFB2Q1MrM2EwS1JTTy9adnZIa3gvdFBQckNc
                bnFleTdydDZHdDcwWEFjeTI4VFBYTWxDN2gzMzdybUt3anVwVDc4bUdvQ0g1bEtGdFppQndVeE4w
                d0o5d25jUkNcbkpXVXFSb2N6eFk5MFg3Rkxyclo0dFBQUCs4S2xqelhSNXVZU09iVHVmZ3ZJTFRh
                MEdZUHplQ3dyQW9HQkFKRzVcbmxSRDJrM2Q1Kyt5T2xOTmJnNXZVTFpMMWY4WW5RZDNmNmg3Ritk
                K0VkWDc4OXJIcnhadTg5VStCdXMyMkFzOVlcbjkwUzhnZzA1RmVlNFlvT0lQb0ZoK25VMjVjejBS
                L1hLWFVpeDB6djZnVmJKendkQXA2R3RhbytTVWkyYmcvOTZcbit2RTMxbFNUQ1pnMkcrZzlEd2xW
                VUhPN1lvNmVacmhZVHVkbUZWaXpBb0dBTDhsekZ1T2NyZFkzZWk0M1I2dzBcbjJwT1FkSDk0UDF1
                dTFJRXA5TTl0NUxwK0FQWEF4UHVNc3ljbEU2a0lLWWNQbVh4UGpTdUQ2Qm9ycUE1d21CenBcbmdy
                MXM3Q05oWUdKQ3R3NndETmw4cHBqWHNNM3AxQmV4Y0Z0c2ppeHVidHVPSC9COWZjQ3p1bW9lSEM1
                bDN1M1VcbkRtSkRwM0YyWFBtUjUrT2Zrbm9mS09NPVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0t
                LVxuIiwKICAiY2xpZW50X2VtYWlsIjogImJ1Y2tldEBzaGluaW5nLWxhbXAtMzY5NTA5LmlhbS5n
                c2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjExNDA1NDA4OTE3NTAzNjYwMDUy
                NCIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9h
                dXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2Vu
                IiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFw
                aXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBz
                Oi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvYnVja2V0JTQwc2hp
                bmluZy1sYW1wLTM2OTUwOS5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIKfQ==

        harborAdminPassword: q1w2e3r4
        secretKey: "ea4Pichuahsha3Wi"
        nginx:
          nodeSelector:
            cloud.google.com/gke-nodepool: "app-pool"
        portal:
          nodeSelector:
            cloud.google.com/gke-nodepool: "app-pool"
        core:
          nodeSelector:
            cloud.google.com/gke-nodepool: "app-pool"
        jobservice:
          nodeSelector:
            cloud.google.com/gke-nodepool: "app-pool"
        registry:
          nodeSelector:
            cloud.google.com/gke-nodepool: "app-pool"
        chartmuseum:
          nodeSelector:
            cloud.google.com/gke-nodepool: "app-pool"
        trivy:
          nodeSelector:
            cloud.google.com/gke-nodepool: "app-pool"
        notary:
          server:
            nodeSelector:
              cloud.google.com/gke-nodepool: "app-pool"
          signer:
            nodeSelector:
              cloud.google.com/gke-nodepool: "app-pool"
        database:
          internal:
            nodeSelector:
              cloud.google.com/gke-nodepool: "app-pool"
        redis:
          internal:
            nodeSelector:
              cloud.google.com/gke-nodepool: "app-pool"
        exporter:
          nodeSelector:
            cloud.google.com/gke-nodepool: "app-pool"
        metrics:
          enabled: false
          serviceMonitor:
            enabled: false
        trace:
          enabled: false



