---
bases:
  - envs/environments.yaml

---
releases:
  - name: ng
    namespace: nginx
    chart: ingress-nginx/ingress-nginx
    version:
    values:
      - controller:
          ingressClass: nginx
          hostNetwork: true
          hostPort:
            enabled: true
            ports:
              http: 80
              https: 443
          config: {}
          service:
            annotations: {}
            enableHttp: true
            enableHttps: true
            loadBalancerIP: {{ .Values.nginx.ip.public }}
            internal:
              enabled: false
          nodeSelector:
            cloud.google.com/gke-nodepool: "app-pool"
          metrics:
            port: 10254
            enabled: false
            service:
              annotations: {}
              omitClusterIP: false
              externalIPs: []
              loadBalancerIP: ""
              loadBalancerSourceRanges: []
              servicePort: 9913
              type: ClusterIP
            serviceMonitor:
              enabled: false
              additionalLabels: {}
              namespace: ""
              namespaceSelector: {}
              scrapeInterval: 30s
            prometheusRule:
              enabled: false
        defaultBackend:
          enabled: true