bases:
  - envs/environments.yaml

---
releases:
  - name: jira
    namespace: cicd
    chart: atlassian/jira
    version: 
    values:
      - replicaCount: 1
        image:
          repository: atlassian/jira-software
          tag: latest
        env:
          JVM_MINIMUM_MEMORY: "1024m"
          JVM_MAXIMUM_MEMORY: "2048m"
        resources:
          requests:
            cpu: "2"
            memory: "6Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        service:
          type: ClusterIP
          port: 80
        ingress:
          create: true
          host: jira.test.home
