---
bases:
  - envs/environments.yaml

---
releases:
  - name: ko
    namespace: kafka
    chart: strimzi/strimzi-kafka-operator
    version:
    values:
      - nodeSelector:
          openebs.io/engine: "mayastor"


