---
bases:
  - envs/environments.yaml

---
releases:
  - name: mayastor
    namespace: mayastor
    chart: mayastor/mayastor
    version:
    values:
      - etcd:
          replicaCount: 3
          persistence:
            enabled: true
            storageClass: "local-path"
        loki-stack:
          enabled: false