---
bases:
  - envs/environments.yaml

---
releases:
  - name: piraeus-operator
    namespace: piraeus-datastore
    chart: ../charts/piraeus
    version:
    values:
      - replicaCount: 1
        installCRDs: true


