---
bases:
  - envs/environments.yaml

---
releases:
  - name: va
    namespace: vault
    chart: ../charts/vault
    version:
    values:
      - server:
          ingress:
            enabled: true
            annotations:
              |
              kubernetes.io/ingress.class: nginx
              kubernetes.io/tls-acme: "true"
              nginx.ingress.kubernetes.io/ssl-redirect: "false"
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: vault.{{ .Values.nginx.domain.public }}
                paths: ['/']
            tls:
              - secretName: vault.{{ .Values.nginx.domain.public }}-tls
                hosts:
                  - vault.{{ .Values.nginx.domain.public }}
          nodeSelector: |
            cloud.google.com/gke-nodepool: "data-pool"
          dataStorage:
            enabled: false
          standalone:
            enabled: "-"



            config: |
              ui = true

              listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              storage "gcs" {
                bucket = "platform-298315-dev-vault-bucket"
              }
              # Example configuration for using auto-unseal, using Google Cloud KMS. The
              # GKMS keys must already exist, and the cluster must have a service account
              # that is authorized to access GCP KMS.
              seal "gcpckms" {
                 project     = "platform-298315"
                 region      = "global"
                 key_ring    = "{{ .Values.vault.key_ring }}"
                 crypto_key  = "{{ .Values.vault.crypto_key }}"
              }
        ui:
          enabled: true

