apiVersion: v1
kind: Service
metadata:
  name: {{ include "teamcity-agent.fullname" . }}
  labels:
    {{- include "teamcity-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "teamcity-agent.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "teamcity-agent.fullname" . }}-headless
  labels:
    {{- include "teamcity-agent.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "teamcity-agent.selectorLabels" . | nindent 4 }}
